defmodule OptimalSystemAgent.Ggen.Templates.TypeScript do
  @moduledoc """
  Fortune 5 Layer 4: TypeScript Project Template Handler

  Generates TypeScript project structure from ODCS specification with proper
  npm configuration, TypeScript settings, and test infrastructure.

  Signal Theory: S=(code,spec,inform,elixir,module)
  """

  require Logger

  @doc """
  Render TypeScript template

  Generates:
  - package.json - npm package configuration
  - tsconfig.json - TypeScript compiler configuration
  - src/index.ts - Entry point
  - src/utils.ts - Utility functions
  - tests/index.test.ts - Test suite
  - .gitignore - Node.js specific rules

  Required variables:
    - project_name: name of the project

  Optional variables:
    - version: version number (default: 1.0.0)
    - description: project description
    - author: author name
  """
  def render(_template, variables) do
    project_name = Map.fetch!(variables, "project_name")
    version = Map.get(variables, "version", "1.0.0")
    description = Map.get(variables, "description", "")
    author = Map.get(variables, "author", "")

    with :ok <- validate_project_name(project_name) do
      files = [
        {"package.json", package_json(project_name, version, description, author)},
        {"tsconfig.json", tsconfig_json()},
        {"src/index.ts", index_ts(project_name)},
        {"src/utils.ts", utils_ts()},
        {"tests/index.test.ts", test_ts(project_name)},
        {".gitignore", gitignore()},
        {"README.md", readme(project_name, description)},
        {".npmrc", npmrc()}
      ]

      {:ok, files}
    end
  end

  # Private

  defp validate_project_name(name) do
    if String.match?(name, ~r/^[a-zA-Z0-9_\-\.\/]+$/) do
      :ok
    else
      {:error, "Project name contains invalid characters: #{name}"}
    end
  end

  defp package_json(project_name, version, description, author) do
    package = %{
      "name" => project_name,
      "version" => version,
      "description" => description,
      "author" => author,
      "license" => "MIT",
      "main" => "dist/index.js",
      "types" => "dist/index.d.ts",
      "files" => ["dist"],
      "scripts" => %{
        "build" => "tsc",
        "test" => "jest",
        "test:watch" => "jest --watch",
        "test:coverage" => "jest --coverage",
        "lint" => "eslint src --ext .ts",
        "format" => "prettier --write src",
        "dev" => "ts-node src/index.ts"
      },
      "devDependencies" => %{
        "@types/jest" => "^29.5.0",
        "@types/node" => "^20.0.0",
        "@typescript-eslint/eslint-plugin" => "^6.0.0",
        "@typescript-eslint/parser" => "^6.0.0",
        "eslint" => "^8.0.0",
        "jest" => "^29.5.0",
        "prettier" => "^3.0.0",
        "ts-jest" => "^29.1.0",
        "ts-node" => "^10.9.0",
        "typescript" => "^5.0.0"
      },
      "engines" => %{
        "node" => ">=16.0.0"
      }
    }

    Jason.encode!(package, pretty: true)
  end

  defp tsconfig_json do
    """
    {
      "compilerOptions": {
        "target": "ES2020",
        "module": "commonjs",
        "lib": ["ES2020"],
        "declaration": true,
        "declarationMap": true,
        "outDir": "./dist",
        "rootDir": "./src",
        "strict": true,
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "resolveJsonModule": true,
        "sourceMap": true,
        "noImplicitAny": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "moduleResolution": "node"
      },
      "include": [
        "src/**/*"
      ],
      "exclude": [
        "node_modules",
        "dist",
        "**/*.test.ts"
      ],
      "ts-node": {
        "esm": false,
        "experimentalEsm": false
      }
    }
    """
  end

  defp index_ts(project_name) do
    """
    /**
     * @file Main entry point for #{project_name}
     * @author Generated by ggen
     */

    import { greet, add } from './utils';

    /**
     * Main function
     */
    async function main(): Promise<void> {
        console.log(greet('World'));
        console.log(`2 + 3 = ${add(2, 3)}`);
    }

    // Run main function
    main().catch((err) => {
        console.error('Error:', err);
        process.exit(1);
    });

    export { main };
    """
  end

  defp utils_ts do
    """
    /**
     * @file Utility functions
     */

    /**
     * Greet someone by name
     * @param name - The person's name
     * @returns A greeting message
     */
    export function greet(name: string): string {
        return `Hello, ${name}!`;
    }

    /**
     * Add two numbers
     * @param a - First number
     * @param b - Second number
     * @returns The sum
     */
    export function add(a: number, b: number): number {
        return a + b;
    }

    /**
     * Subtract two numbers
     * @param a - First number
     * @param b - Second number
     * @returns The difference
     */
    export function subtract(a: number, b: number): number {
        return a - b;
    }

    /**
     * Multiply two numbers
     * @param a - First number
     * @param b - Second number
     * @returns The product
     */
    export function multiply(a: number, b: number): number {
        return a * b;
    }

    /**
     * Divide two numbers
     * @param a - Dividend
     * @param b - Divisor
     * @returns The quotient
     * @throws Error if divisor is zero
     */
    export function divide(a: number, b: number): number {
        if (b === 0) {
            throw new Error('Division by zero');
        }
        return a / b;
    }
    """
  end

  defp test_ts(_project_name) do
    """
    import { greet, add, subtract, multiply, divide } from '../src/utils';

    describe('utils', () => {
        describe('greet', () => {
            it('should greet a person', () => {
                expect(greet('Alice')).toBe('Hello, Alice!');
            });

            it('should handle empty names', () => {
                expect(greet('')).toBe('Hello, !');
            });
        });

        describe('arithmetic functions', () => {
            it('should add two numbers', () => {
                expect(add(2, 3)).toBe(5);
                expect(add(0, 0)).toBe(0);
                expect(add(-1, 1)).toBe(0);
            });

            it('should subtract two numbers', () => {
                expect(subtract(5, 3)).toBe(2);
                expect(subtract(0, 0)).toBe(0);
                expect(subtract(1, 2)).toBe(-1);
            });

            it('should multiply two numbers', () => {
                expect(multiply(2, 3)).toBe(6);
                expect(multiply(0, 5)).toBe(0);
                expect(multiply(-2, 3)).toBe(-6);
            });

            it('should divide two numbers', () => {
                expect(divide(6, 2)).toBe(3);
                expect(divide(10, 4)).toBe(2.5);
            });

            it('should throw on division by zero', () => {
                expect(() => divide(5, 0)).toThrow('Division by zero');
            });
        });
    });
    """
  end

  defp gitignore do
    """
    # Node modules
    node_modules/
    package-lock.json
    yarn.lock

    # Build output
    dist/
    build/

    # IDE
    .vscode/
    .idea/
    *.swp
    *.swo
    *~
    .DS_Store

    # Environment
    .env
    .env.local
    .env.*.local

    # Test coverage
    coverage/
    .nyc_output/

    # Logs
    logs/
    *.log
    npm-debug.log*
    yarn-debug.log*
    yarn-error.log*
    """
  end

  defp npmrc do
    """
    # npm configuration
    legacy-peer-deps=true
    """
  end

  defp readme(project_name, description) do
    """
    # #{project_name}

    #{description}

    ## Getting Started

    ### Prerequisites

    - Node.js 16+
    - npm 7+

    ### Installation

    ```bash
    npm install
    ```

    ### Development

    ```bash
    npm run dev
    ```

    ### Building

    ```bash
    npm run build
    ```

    ### Testing

    ```bash
    npm test
    ```

    ### Linting

    ```bash
    npm run lint
    ```

    ## Project Structure

    ```
    .
    ├── src/           # Source code
    │   ├── index.ts   # Entry point
    │   └── utils.ts   # Utility functions
    ├── tests/         # Test files
    ├── dist/          # Compiled output
    └── package.json   # Dependencies
    ```

    ## License

    MIT
    """
  end
end
