defmodule OSA.Semconv do
  @moduledoc """
  Umbrella module providing easy access to all ChatmanGPT semantic convention attribute modules.

  Generated by OTel Weaver from `semconv/model/`. Do not edit the individual modules —
  regenerate with:

      weaver registry generate -r ./semconv/model -t ./semconv/templates elixir ./OSA/lib/osa/semconv/

  ## Usage in Chicago TDD tests

      alias OpenTelemetry.SemConv.Incubating.HealingAttributes

      test "healing diagnosis emits deadlock failure_mode attribute" do
        result = Diagnosis.classify(%{error: :circular_wait})
        assert result.failure_mode == HealingAttributes.healing_failure_mode_values().deadlock
      end

  ## Available modules

  - `OpenTelemetry.SemConv.Incubating.HealingAttributes`
  - `OpenTelemetry.SemConv.Incubating.AgentAttributes`
  - `OpenTelemetry.SemConv.Incubating.ConsensusAttributes`
  - `OpenTelemetry.SemConv.Incubating.McpAttributes`
  - `OpenTelemetry.SemConv.Incubating.A2aAttributes`
  - `OpenTelemetry.SemConv.Incubating.CanopyAttributes`
  - `OpenTelemetry.SemConv.Incubating.WorkflowAttributes`
  - `OpenTelemetry.SemConv.Incubating.BosAttributes`
  - `OpenTelemetry.SemConv.Incubating.ProcessAttributes`
  - `OpenTelemetry.SemConv.Incubating.ChatmangptAttributes`
  """
end
