defmodule OptimalSystemAgent.Store.DecisionNode do
  @moduledoc """
  Ecto schema for decision graph nodes.

  Nodes are the epistemic units of the decision graph. Each node represents
  one of five types: decision, option, goal, observation, or revisit.

  The `:confidence` field is a float in [0.0, 1.0] representing how certain
  the team is about this node. Cascade propagation updates this field when
  upstream nodes change.

  The `:metadata` field is a free-form map for type-specific data (e.g.
  option scores, observation sources, revisit triggers).

  Primary key is a string generated by `OptimalSystemAgent.Utils.ID.generate/1`.
  Timestamps are managed by Ecto (`:inserted_at`, `:updated_at`).
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :string, autogenerate: false}
  @timestamps_opts [type: :naive_datetime_usec]

  schema "decision_nodes" do
    field(:type, :string)
    field(:title, :string)
    field(:description, :string)
    field(:status, :string, default: "active")
    field(:confidence, :float, default: 1.0)
    field(:agent_name, :string)
    field(:team_id, :string)
    field(:session_id, :string)
    field(:metadata, :map, default: %{})

    timestamps()
  end

  @required_fields [:id, :type, :title, :team_id]
  @optional_fields [
    :description,
    :status,
    :confidence,
    :agent_name,
    :session_id,
    :metadata
  ]

  @valid_types ~w(decision option goal observation revisit)
  @valid_statuses ~w(active superseded archived completed)

  def changeset(node \\ %__MODULE__{}, attrs) do
    node
    |> cast(attrs, @required_fields ++ @optional_fields)
    |> validate_required(@required_fields)
    |> validate_inclusion(:type, @valid_types)
    |> validate_inclusion(:status, @valid_statuses)
    |> validate_number(:confidence,
      greater_than_or_equal_to: 0.0,
      less_than_or_equal_to: 1.0
    )
  end
end
