defmodule OptimalSystemAgent.Store.DecisionEdge do
  @moduledoc """
  Ecto schema for decision graph edges.

  Edges are typed directed relationships between two nodes. The `:weight`
  field (0.0–1.0) controls how much confidence propagates through this edge
  during a cascade operation. A weight of 1.0 means full propagation; 0.0
  means the edge carries no confidence signal.

  The `:rationale` field records why this relationship was asserted — useful
  for narrative generation and audit trails.

  Primary key is a string generated by `OptimalSystemAgent.Utils.ID.generate/1`.
  Only `:inserted_at` is tracked (edges are immutable once created).
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :string, autogenerate: false}
  @timestamps_opts [type: :naive_datetime_usec]

  schema "decision_edges" do
    field(:source_id, :string)
    field(:target_id, :string)
    field(:type, :string)
    field(:rationale, :string)
    field(:weight, :float, default: 1.0)

    timestamps(updated_at: false)
  end

  @required_fields [:id, :source_id, :target_id, :type]
  @optional_fields [:rationale, :weight]

  @valid_types ~w(leads_to chosen rejected requires blocks enables supersedes supports revises summarizes)

  def changeset(edge \\ %__MODULE__{}, attrs) do
    edge
    |> cast(attrs, @required_fields ++ @optional_fields)
    |> then(&put_default_if_not_in_attrs(&1, attrs, :weight, 1.0))
    |> validate_required(@required_fields)
    |> validate_inclusion(:type, @valid_types)
    |> validate_number(:weight,
      greater_than_or_equal_to: 0.0,
      less_than_or_equal_to: 1.0
    )
  end

  defp put_default_if_not_in_attrs(changeset, attrs, field, default) do
    if Map.has_key?(attrs, field) or Map.has_key?(attrs, to_string(field)) do
      changeset
    else
      Ecto.Changeset.force_change(changeset, field, default)
    end
  end
end
